name: Unittest
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Validate python version
        run: python --version

      - name: Install dependencies
        run: pip install pytest

      - name: Run Test
        run: python -m pytest tests/
